services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3003:3000"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8003:8000"

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest

    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: